### ISSUE TITLE
No reading url from config

### ISSUE THREAD

**Issue by s4kibs4mi** [emqtt/emq-web-hook#10]

**Comment by turtleDeng** [comment]
@s4kibs4mi Do you restart the broker after modifying the configuration?

**Comment by s4kibs4mi** [comment]
Not the broker. Restarted the plugin. @turtleDeng

**Comment by s4kibs4mi** [comment]
@turtleDeng , Its working now. But problem is if rest api on port 8080 failed to start then web hook is not working.

**Comment by turtleDeng** [comment]
@s4kibs4mi  Yes, if the web_hook access API is invalid, it will disconnect the client.
