### ISSUE TITLE
Could you explain how we can use this web-hook?

### ISSUE THREAD

**Issue by tremoteye** [emqtt/emq-web-hook#14]
I just started web-hook plugin. 
if I would like to receive each hook message, What should I do?

Ex) turn on HTTP Server to receive web-hook?

**Comment by s4kibs4mi** [comment]
@tremoteye , First of all you need a web server to receive hook events. Then change web server address in /etc/emq_web_hook.conf file `web.hook.api.url = http://127.0.0.1`. And you are done.

**Comment by arden** [comment]
我觉得应该做一些例子，要不然大家都不知道到底怎么用。

**Comment by s4kibs4mi** [comment]
@arden Can you please write in english ?

**Comment by marcotuna** [comment]
We need some examples for NodeJS, PHP or something else.

**Comment by satrox28** [comment]
Can somebody tell me what need to be configured on the Api server.
