### ISSUE TITLE
Example of changing a parameter using emq-web-hook

### ISSUE THREAD

**Issue by Eric24** [emqtt/emq-web-hook#17]
Does emq-web-hook support the ability change change a parameter, as does https://github.com/emqtt/emq-lua-hook? For example, changing the topic when a client subscribes?

I understand how emq-web-hook works from a logging/notification standpoint, where data is sent to the URL, but it's not clear what the response options are, if any. A simple example would be much appreciated.

Thank you in advance.

**Comment by HJianBo** [comment]
**emq-web-hook** doesn't support modifying topic in a way like **emq-lua-hook**

If you want to support, you have to modify the code, for example:
The original:
https://github.com/emqtt/emq-web-hook/blob/fc58e066707a853ce6f3293dd02a9415f8a973b2/src/emq_web_hook.erl#L74-L84

Change to:
```
on_client_subscribe(ClientId, Username, TopicTable, {Filter}) -> 
    % do your job here
    case SomeCondition of
        true  -> {ok, NewTopicTable};
        false -> false
    end.
```
But we don't recommend that
