### ISSUE TITLE
unsubcribe action name is wrong

### ISSUE THREAD

**Issue by nb7123** [emqtt/emq-web-hook#9]
unsubscribe action name: 
{
    "action":"client_unsubscribe",
    "client_id":"C_1492410235117",
    "username":"C_1492410235117",
    "topic":"world"
}
not is:
{
    "action":"client_subscribe",
    "client_id":"C_1492410235117",
    "username":"C_1492410235117",
    "topic":"world"
}

**Comment by nb7123** [comment]
client connected:
{
    "action":"client_connected",
    "client_id":"C_1492410235117",
    "conn_ack":0
}
not:
{
    "action":"session_created",
    "client_id":"C_1492410235117",
    "conn_ack":0
}

**Comment by s4kibs4mi** [comment]
Readme updated
